name: Events Demo 1
on: 
  pull_request:
    # types: [opened, edited]
    types:
      - opened
    branches:
      # only pushes to the following branches would trigger this workflow
      - main # it only covers "main"
      - 'dev-*' # e.g. dev-new, dev-this-is-new
      - 'feat/**' # e.g. feat/new-feat/new/button
  workflow_dispatch:
  push:
    branches:
      # only pushes to the following branches would trigger this workflow
      - main # it only covers "main"
      - 'dev-*' # e.g. dev-new, dev-this-is-new
      - 'feat/**' # e.g. feat/new-feat/new/button
    # whem we push to the 3 branches, this workflow will be run
    # if we did not change a file in this .github/workflow folder
    paths-ignore:
      - '.github/workflow/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
