name: Deploy Project
on: [push, workflow_dispatch]
# workflow-lv env var
env:
  MONGODB_DB_NAME: gha-demo
# this workflow has 2 jobs that are running in //
jobs:
  test: 
    # job-lv env var
    # env:
      # MONGO_CLUSTER_ADDRESS: x.x.x.x
      # MONGO_USERNAME: abc123
      # MONGO_PASSWORD: abc123
    runs-on: ubuntu-latest
    steps:
      - name: Test environment variable
        run: echo "$MONGODB_DB_NAME"
      - name: Get code
        uses: actions/checkout@v3 # use the "uses" keyword to use an action
        # "with" keyword provides configuration to the actions
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  # another job
  deploy:
    # the deploy job needs the test job to be finished successfully before staring
    # needs: [job1, job2] to wait for multiple jobs to finish
    # needs: test
    # every job has its own runner even if they're in the same workflow
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project        
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
