name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix: 
        node-version: [12, 14, 16]
        # Tell GitHub Actions to run this built job multiple times, once per value, in that operating system array.
        # Those jobs will be run in // by default
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ martix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
