name: Matrix Demo
on: push
jobs:
  build:
    # If one matrix job fails, the other jobs are canceled and skipped.
    # Set continue-on-error to true will tell GitHub Actions 
    # to continue executing jobs that are related to this matrix even if some jobs for some combinations failed.
    continue-on-error: true
    strategy:
      matrix: 
        node-version: [12, 14, 16]
        # Tell GitHub Actions to run this built job multiple times, once per value, in that operating system array.
        # Those jobs will be run in // by default
        operating-system: [ubuntu-latest, windows-latest]
        # "include" allows you to add a list with dashes of key values that should be included without adding a bunch of new combinations
        # it avoids the unwanted combination of windows-latest and node 18
        include:
          - node-version: 18
            operating-system: ubuntun-latest
            npm: 6 # you can even add brand-new keys that weren't even specified up here
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ martix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
