name: Public Cloud Scanning
on:
  push:
    branches:
      - main
jobs:
  # for runner 1
  upload-cache-to-hagithub:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
  # for runner 2
  oss-scanning:
    needs: upload-cache-to-hagithub
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      # - name: Start OSS scanning
