name: Reusable Deploy
# The "on" trigger's "workflow_call" event help make the reusable workflow callable by others
on: 
  workflow_call:
    # Any inputs this reusable workflow needs
    inputs: 
      artifact-name: 
        description: The name of the deployable artifact files
        # "required" indicates whether this workflow should fail if we're not getting this input
        required: false
        default: dist
        type: string
    # secrets:
      # some-secret:
        # required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files to check whether downloading the artifact works
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."
