name: Workflow 1
run-name: Lint, Test & Deploy on "push" by ${{ github.actor }}
on: push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Get code."
      - name: Get code
        uses: actions/checkout@v3
      - run: echo "Install dependencies."
      - run: npm ci
      - run: echo "Lint."
      - run: npm eslint --ext .jsx --fix src
      - run: echo "Test."
      - run: npm vitest run
      - run: echo "Deploy."
