name: Handle Issues
run-name: Output Event Details on "issues" by ${{ github.actor }}
# the workflow will be triggered whenever anything related to issue happens on the repo
on: issues
jobs:
  Output-Info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"
